
<html>
<head>
    <title>User</title>
</head>
<body>
<table class="infobox" style="width:25.5em;" data-name="Автомобиль">
    <p align="right">
        <tbody>
        <tr>
            <th class="plainlist">User id</th>
            <td class="plainlist">
                <a>${user.id}</a>
            </td>
        </tr>
        <tr>
            <th class="plainlist">email</th>
            <td class="plainlist">
                <a><a>${user.email}</a></a>
            </td>
        </tr>
        <tr>
            <th class="plainlist">country</th>
            <td class="plainlist">
                <a>${user.country}</a>
            </td>
        </tr>
        <tr>
            <th class="plainlist">gender</th>
            <td class="plainlist">
                <a  name="waste"><a>${user.gender}</a></a>
            </td>
        </tr>
        <tr>
            <th class="plainlist">date</th>
            <td class="plainlist">
                <a  name="waste"><a>${user.date}</a></a>
            </td>
        </tr>
        </tbody>
    </p>
</table>
</body>
</html>
